# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# importamos la libreria zeep para implementar el servicio SOAP
from zeep import Client

from Client.principal import Ui_MainWindow


class Ui_Dialog(object):
    url = "https://astrocaribbean.tech/ws/SOAPService?wsdl"
    # definimos nuestro cliente con la URL
    client = Client(url)

    def __init__(self):
        self.app = None

    def setupUi(self, Dialog):
        Dialog.setObjectName("Login")
        Dialog.resize(480, 640)
        self.TXTusername = QtWidgets.QLineEdit(Dialog)
        self.TXTusername.setGeometry(QtCore.QRect(100, 210, 271, 31))
        self.TXTusername.setObjectName("TXTusername")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 80, 171, 101))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.passwordTXT = QtWidgets.QLineEdit(Dialog)
        self.passwordTXT.setGeometry(QtCore.QRect(100, 270, 271, 31))
        self.passwordTXT.setObjectName("passwordTXT")
        self.loginBTN = QtWidgets.QPushButton(Dialog)
        self.loginBTN.setGeometry(QtCore.QRect(190, 350, 93, 28))
        self.loginBTN.setObjectName("loginBTN")
        self.loginBTN.clicked.connect(self.login)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Iniciar Sesion"))
        self.label.setGeometry(QtCore.QRect(150, 80, 301, 101))
        self.loginBTN.setText(_translate("Dialog", "Entrar"))

    def login(self):
        if self.TXTusername.text() != "" and self.passwordTXT.text() != "":
            self.user = self.client.service.login(self.TXTusername.text(), self.passwordTXT.text())
            if self.user is None:
                error = QtWidgets.QErrorMessage()
                error.setWindowModality(QtCore.Qt.WindowModal)
                error.showMessage("Usuario o contraseña incorrectos")
                error.setWindowTitle("Error")
                error.exec_()
            else:
                self.openWindow()

        else:
            error = QtWidgets.QErrorMessage()
            error.setWindowModality(QtCore.Qt.WindowModal)
            error.showMessage("Asegurese de que llene todas las informaciones correspondientes")
            error.setWindowTitle("Error")
            error.exec_()

    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.user = self.user
        self.ui.setupUi(self.window)
        Dialog.hide()
        self.window.show()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
